-- CRIACÃO DE TABELAS

CREATE TABLE CATEGORIA(
	CATEGORIA_ID 	SERIAL PRIMARY KEY,
	DESC_CATEGORIA 	VARCHAR(150) NOT NULL
);

CREATE TABLE UF(
	UF_ID 			SERIAL PRIMARY KEY,
	SIGLA_UF 		CHAR(2) NOT NULL,
	DESC_UF 		VARCHAR(150) NOT NULL
);

CREATE TABLE CIDADE(
	CIDADE_ID 		SERIAL PRIMARY KEY,
	DESC_CIDADE 	VARCHAR(150) NOT NULL,
	ID_UF_FK  		INT,
	FOREIGN KEY (ID_UF_FK) REFERENCES UF(UF_ID)
);

CREATE TABLE PRODUTOS(
	PRODUTO_ID 		SERIAL PRIMARY KEY,
	DESC_PRODUTO 	VARCHAR(150) NOT NULL,
	PRECO_UNI 		DECIMAL(18,2) NOT NULL,
	QNT_ESTOQUE 	INT NOT NULL, 
	OBS_PROD 		VARCHAR(150) NOT NULL,
	CATEGORIA_ID_FK INT,
	FOREIGN KEY (CATEGORIA_ID_FK) REFERENCES CATEGORIA(CATEGORIA_ID)
);

CREATE TABLE CLIENTES(
	CLIENTE_ID 		SERIAL PRIMARY KEY,
	NOME_CLI 		VARCHAR (100) NOT NULL,
	CPF_CNPJ_CLI 	VARCHAR(18) NOT NULL,
	EMAIL_CLI 		VARCHAR(60) NOT NULL,
	ENDERECO_CLI 	VARCHAR(100) NOT NULL,
	CEP_CLI 		VARCHAR(9) NOT NULL,
	UF_ID_FK		INT,	
	ID_CIDADE_FK	INT,
	FOREIGN KEY (UF_ID_FK) REFERENCES UF(UF_ID),
	FOREIGN KEY (ID_CIDADE_FK) REFERENCES CIDADE(CIDADE_ID)	
);

CREATE TABLE PEDIDOS(
	PEDIDO_ID 		SERIAL PRIMARY KEY,
	DATA_PED 		DATE DEFAULT CURRENT_DATE, --insere a data automaticamente conforme onde o sql esta rodando
	TOTAL_PED 		NUMERIC(18,2) NOT NULL,
	ID_CLIENTE_FK 	INT,
	FOREIGN KEY	(ID_CLIENTE_FK) REFERENCES CLIENTES(CLIENTE_ID)
);

CREATE TABLE PEDIDOS_PRODUTOS(
	ID_PEDIDO_FK 	INT,
	ID_PRODUTO_FK	INT,
	DESC_FINAL 		VARCHAR(60) NOT NULL,
	QNT_FINAL		INT,
	VAL_UNI_FINAL	DECIMAL(18,2),
	VALOR_TOT_FINAL	DECIMAL(18,2),
	PRIMARY KEY (ID_PEDIDO_FK, ID_PRODUTO_FK),
	FOREIGN KEY (ID_PEDIDO_FK) REFERENCES PEDIDOS(PEDIDO_ID),
    FOREIGN KEY (ID_PRODUTO_FK) REFERENCES PRODUTOS(PRODUTO_ID)
);

-- EXIBIR RESULTADOS

SELECT VAL_UNI_FINAL * QNT_FINAL AS TOTAL_ITEM
FROM PEDIDOS_PRODUTOS;

-- POVOANDO TABELAS

INSERT INTO CATEGORIA(DESC_CATEGORIA)
	VALUES
		('Periféricos');

INSERT INTO UF(SIGLA_UF, DESC_UF)
	VALUES
		('PR', 'Paraná');
		
INSERT INTO CIDADE(DESC_CIDADE)
	VALUES
		('Interior');

INSERT INTO PRODUTOS(DESC_PRODUTO, PRECO_UNI, QNT_ESTOQUE, OBS_PROD, CATEGORIA_ID_FK)
	VALUES
		('Teclado magnetico', 350.80, 20, 'Sem RGB', 4),
		('Monitor 144hz 24pol', 1000, 45, 'Painel IPS', 4),
		('Mouse Gamer', 250, 100, 'Sensor PAW3950', 4);

INSERT INTO CLIENTES(CLIENTE_ID, NOME_CLI, CPF_CNPJ_CLI, EMAIL_CLI, ENDERECO_CLI, CEP_CLI)
	VALUES
		(4, 'Rafael Antonio', '111.222.333-44', 'rafael@email.com', 'Rua Nome Inventado', '12345-678');

INSERT INTO PEDIDOS(TOTAL_PED, ID_CLIENTE_FK)
	VALUES
		(1600.80, 4);

INSERT INTO PEDIDOS_PRODUTOS (DESC_FINAL, QNT_FINAL, VAL_UNI_FINAL, VALOR_TOT_FINAL)
VALUES
    ('Teclado magnetico', 2, 350.80, 701.60),
    ('Monitor 144hz 24pol', 1, 1000.00, 1000.00);


--TESTES
	select * from pedidos
	SELECT COUNT(*) FROM pedidos_produtos;
